### ISSUE TITLE
Add Search component with speech search capability

### ISSUE THREAD

**Issue by vinodloha** [pagesource/atomic-react-components#100]
**Requirement**
Add Search component with speech search capability. 

**Additional context**

<img width="676" alt="Screenshot 2019-10-18 at 7 46 52 AM" src="https://user-images.githubusercontent.com/8122967/67060689-7ce27c80-f17b-11e9-91b7-f737a5b6c3a9.png">

**Comment by iamsauravsingh** [comment]
Hi @vinodloha @manishekhawat,
I am saurav, Can I pick this issue?
