### ISSUE TITLE
Integrate styleguidist

### ISSUE THREAD

**Issue by bhardwajamit0890** [pagesource/atomic-react-components#149]
https://github.com/styleguidist/react-styleguidist

**Comment by manishekhawat** [comment]
details please around why do we need it and what purpose will it solve

**Comment by vinodloha** [comment]
> details please around why do we need it and what purpose will it solve

@bhardwajamit0890 Can you respond on this? ;)

**Comment by bhardwajamit0890** [comment]
@manishekhawat  
@vinodloha have already implemented MDX, hence it is not required now. It was all about to publish the style guide for components .
