### ISSUE TITLE
Upgrade the storybook env with additional capabilities

### ISSUE THREAD

**Issue by vinodloha** [pagesource/atomic-react-components#58]
- Auto Doc generation 
- Code Snippet Viewer
- Better showcase structure 
- Upgrade the version with add-ons

**Comment by manishekhawat** [comment]
Added the above asked features and PR raised https://github.com/pagesource/atomic-react-components/pull/69

Pending feature : live edit of code

**Comment by manishekhawat** [comment]
closing this feature request as PR already merged. Raising a new feature request for Live Code Edit in Story Book
