### ISSUE TITLE
Added data locators for progressive testing 

### ISSUE THREAD

**Issue by vinodloha** [pagesource/atomic-react-components#65]
Should be available in all Atoms. 
Should be able to put a default unique value in data attribute if prop is not passed.

**Comment by vinodloha** [comment]
This has been implement for one component Atom Input via #66. The same needs to happen for other atoms. Also Fallback for Unique Id needs to be utilised.

**Comment by manishekhawat** [comment]
Finished the complete implementation and raised PR for all the atoms. https://github.com/pagesource/atomic-react-components/pull/67

**Comment by manishekhawat** [comment]
Closing this, add the element locator work for current atoms is complete.
