### ISSUE TITLE
Add Notification Component

### ISSUE THREAD

**Issue by manishekhawat** [pagesource/atomic-react-components#84]
<img width="1418" alt="Screen Shot 2019-10-17 at 7 46 25 PM" src="https://user-images.githubusercontent.com/1632381/67017085-d6649000-f116-11e9-8c83-2c706ee727ce.png">

**Comment by mankumar66** [comment]
@vinodloha   @manishekhawat @ankurkakroo2 
Hi,
Could you please provide the font-family to be used here. 
Also, could you please review my initial commit corresponding to this feature:  https://github.com/mankumar66/atomic-react-components/tree/feature/notification-component

Thanks and Regards,
Manisha

**Comment by bhardwajamit0890** [comment]
@mankumar66  Please raise pr that needs to be reviewed
